app:
    resource: '@AppBundle/Controller/'
    type: annotation

page:
    resource: '@PageBundle/Resources/config/routing.yml'

category:
    resource: '@CategoryBundle/Resources/config/routing.yml'

comment:
    resource: '@CommentBundle/Resources/config/routing.yml'
