page_list:
    path: /page
    defaults: { _controller: PageBundle:Page:list }

page_add:
    path: /page/add
    defaults: { _controller: PageBundle:Page:add }

page_view:
    path: /page/{id}
    defaults: { _controller: PageBundle:Page:view }
    requirements:
        page: '\d+'

page_comments:
    path: /page/{id}/comments
    requirements:
        page: '\d+'

page_edit:
    path: /page/{id}/edit
    defaults: { _controller: PageBundle:Page:edit }
    requirements:
        page: '\d+'

page_delete:
    path: /page/{id}/delete
    defaults: { _controller: PageBundle:Page:remove }
    requirements:
        page: '\d+'